# Check if the project properly installs and builds all dependencies
build_job:
  stage: build
  script:
    - cd /var/www/html/app
    - npm install

# Deploy the API and place config file
deploy_api_job:
  stage: deploy
  only:
    - production
  script:
    - cp -r . /var/www/html/$CI_BUILD_REF
    - ln -s ./$CI_BUILD_REF /var/www/templink
    - mv -Tf /var/www/html/templink /var/www/html/app
    - cp /var/www/html/production.json /var/www/html/app/production.json
# Install all dependencies and restart the process
install_api_job:
  stage: dependencies
  only:
    - production
  script:
    - cd /var/www/html/app/
    - npm install --production
# Reboot the process
reboot_job:
  stage: reboot
  only:
    - production
  script:
    - cd /var/www/html/app
    - pm2 stop api
    - pm2 delete api
    - NODE_ENV=production pm2 start --name api app.js

stages:
  - build
  - deploy
  - reboot
